// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHo91vhiVVdBpD1TBXu4MnatdroBtLWvY',
    appId: '1:827129271732:web:64cdbe97eb96cbbf230ee1',
    messagingSenderId: '827129271732',
    projectId: 'hardware-2c430',
    authDomain: 'hardware-2c430.firebaseapp.com',
    storageBucket: 'hardware-2c430.firebasestorage.app',
    measurementId: 'G-YKDKQLEGS2',
    databaseURL: 'https://hardware-2c430-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpZSLddRxRIAe3KKl9_0xEPs_7IknlcNs',
    appId: '1:827129271732:android:57846313cee089a7230ee1',
    messagingSenderId: '827129271732',
    projectId: 'hardware-2c430',
    storageBucket: 'hardware-2c430.firebasestorage.app',
    databaseURL: 'https://hardware-2c430-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9tFXidxqKdkMzRKXwi-8JfUoyC-p8_l0',
    appId: '1:827129271732:ios:2055cfe19a0b8cb5230ee1',
    messagingSenderId: '827129271732',
    projectId: 'hardware-2c430',
    storageBucket: 'hardware-2c430.firebasestorage.app',
    iosBundleId: 'com.example.hardwarelab',
    databaseURL: 'https://hardware-2c430-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9tFXidxqKdkMzRKXwi-8JfUoyC-p8_l0',
    appId: '1:827129271732:ios:2055cfe19a0b8cb5230ee1',
    messagingSenderId: '827129271732',
    projectId: 'hardware-2c430',
    storageBucket: 'hardware-2c430.firebasestorage.app',
    iosBundleId: 'com.example.hardwarelab',
    databaseURL: 'https://hardware-2c430-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHo91vhiVVdBpD1TBXu4MnatdroBtLWvY',
    appId: '1:827129271732:web:090967c6f8b07fa9230ee1',
    messagingSenderId: '827129271732',
    projectId: 'hardware-2c430',
    authDomain: 'hardware-2c430.firebaseapp.com',
    storageBucket: 'hardware-2c430.firebasestorage.app',
    measurementId: 'G-2MGXZFCTPV',
    databaseURL: 'https://hardware-2c430-default-rtdb.asia-southeast1.firebasedatabase.app',
  );
}
